apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: recurrence-cron
  namespace: taskora
spec:
  type: bindings.cron
  version: v1
  metadata:
    - name: schedule
      value: "@every 1m"
    - name: route
      value: "/api/recurrence/check"
