apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: taskora-statestore
  namespace: taskora
spec:
  type: state.postgresql
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: taskora-secrets
        key: DATABASE_URL
    - name: tableName
      value: "dapr_state"
    - name: keyPrefix
      value: "name"
